[로또 미션] 김명지 미션 제출합니다.
next-step/java-lotto-clean-playground pull request #24
Opened 2024-05-21 17:05 UTC by Starlight258

안녕하세요 진영님 !
로또 2단계 미션을 완료했습니다 😁

## 궁금한 점
- 댓글에 남겼습니다!

✅ 구현된 코드에 대한 설명은 `README.md`에서 보실 수 있습니다 ! 

리뷰 부탁드립니다 !! 감사합니다~ 🙇‍♀️

2024-05-21 17:16 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/Lottos.java
> +        int lottoCount = Lotto.calculateLottoCount(price);
Lottos 클래스에서 다른 클래스의 calculateLottoCount 메서드를 직접 호출하고 있는데, 이렇게 구현하는 것이 좋은 방법인지 궁금합니다. 클래스 간의 결합도를 낮추기 위한 좋은 방법이 있을까요?

2024-05-27 15:14 UTC, jinyoungchoi95 requested changes
안녕하세요 명지님 😃

몇가지 코멘트남겨두었으니 확인부탁드려요.

감사합니다🙇‍♂️

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/Lottos.java
> +        int lottoCount = Lotto.calculateLottoCount(price);
어짜피 `Lotto`의 일급컬랙션이기 때문에 `Lotto`에 의존되어있는 구조자체가 이상하지는 않아요.

가격에 대한 책임이라고 한다면 그냥 로또의 가격은 `Price`가 가져도 되는 것 아닐까싶어요. 로또라는 네이밍으로 인해서 `Lotto`가 가격을 가져야한다기보다는 적절한 책임이 어디에 가야할까를 고민해보면 가격에 대한 책임은 모두 `Price`가 가지는 게 맞아보이네요.

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/LottoNumber.java
> +public class LottoNumber {
👍

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/LottoNumber.java
> +        }
1이상 45 이하라면 `END_EXCLUSIVE_NUMBER`는 45를 두어 로직을 만드는게 어떨까싶어요.

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/LottoNumber.java
> +    public LottoNumber(int number) {
1~45만을 사용한다면 값을 캐싱해보는 방법도 있어요.

`Integer`나 `Long`의 구현체를 확인해보시면 도움이 될 것 같아요.

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/Price.java
> +    }
0으로 나뉘면 어떻게 되나요?

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/Lotto.java
> +                        }))
함수가 좀 복잡한 것 같아요. 자바 8에서 함수형프로그래밍이 나온 이유를 생각해보면 행위를 잘 표현하기 위해서 stream이 나온 것인데, 로직이 좀 복잡하지 않나요? 메소드로 분리하거나 할수도 있을 것 같아요.

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/Lotto.java
> +    }
`dividedBy`의 결과가 `getValue()`로만 사용된다면 반환값을 `Price`가 아닌 사용되는 int를 바로 반환하게끔 하여도 되지 않을까요?

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/test/java/org/duckstudy/model/lotto/LottosTest.java
> +                    .toList();
테스트를 위해 생성하는 로직이 너무 복잡해요. 아래와 같은 방법을 고려해보세요.

1. 생성자에서 추가로 제공하면 되는 것 아닌가
```java
public Lotto(LottoNumber... lottoNumbers) {
    this(List.of(lottoNumbers));
}
```
2. 별도의 생성하는 메소드로 분리한다.

2가 일반적으로 생각나는 방법일텐데 1에서 생성자를 추가하는 방법을 고민해보시면 좋을 것 같아요. 테스트를 위한 생성자를 제가 이전 피드백에서 드렸는지 잘 기억이 나지 않는데, 테스트를 위한 생성자와 테스트를 위한 메소드에 대한 고민을 한번 해보시면 좋을 것 같아요.

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/LottoResult.java
> +    }
private 메소드여야겠네요.

2024-05-27 15:14 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/LottoResult.java
> +        Price profit = new Price(INITIAL_PRICE);
0원을 가진 `Price`는 `Price`에서 정적팩토리메소드로 제공하는 것이 더 적절한 책임이 아닐까요?

2024-05-28 10:12 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/Lottos.java
> +        int lottoCount = Lotto.calculateLottoCount(price);
그렇군요 !! 가격에 대한 책임은 모두 `Price`에 있는게 더 적절해 보이네요 !

2024-05-28 10:50 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/LottoNumber.java
> +        }
그렇게 하면 요구사항이 코드에 명확하게 드러나겠네요! 수정하겠습니다 !

2024-05-28 11:41 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/LottoNumber.java
> +    public LottoNumber(int number) {
`Integer` 클래스 구현체를 확인해봤는데, 기본적으로 -128부터 127까지 범위의 정수값에 대해서는 미리 생성하여 `IntegerCache`라는 캐시에 저장해두네요! 
`LottoNumber`에서도 1 ~ 45사이의 값의 객체들만 생성되기 때문에, 캐시에 저장해서 재사용할 수 있도록 하는게 좋겠어요~ 
감사합니다 !!

2024-05-28 12:50 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/Price.java
> +    }
헉 0원으로 나눌 경우를 미처 생각하지 못했네요..! 테스트에도 추가하겠습니다 !

2024-05-28 13:14 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/Lotto.java
> +                        }))
맞습니다 ! 리팩토링하겠습니다 !!

2024-05-29 05:55 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/Lotto.java
> +    }
맞습니다! `divideBy`에서 int 결과값만 사용하기 때문에 굳이 `Price`로 반환해서 `getValue()`를 호출할 필요가 없을 것 같아요.
감사합니다~

2024-05-29 07:57 UTC, Starlight258 commented on src/test/java/org/duckstudy/model/lotto/LottosTest.java
> +                    .toList();
생각해보면 좋은 주제네요 감사합니다 😊

테스트를 위한 메서드를 생성하는 것이 항상 좋은 선택은 아니지만 테스트를 용이하게 하기 위해 적당히 선택하면 좋을 것 같아요!
언급해주신 코드에서도 구현된 메서드만 가지고 테스트를 하려다보니 중복되는 코드도 많고 굉장히 복잡해졌네요..!
테스트를 위한 코드를 주석이나 메서드 명으로 프로덕션 코드와 구분만 잘 짓는다면, 상황에 따라 유연하게 선택하면 좋을 것 같아요.

```java
public static Lotto createLottoForTest(int... values) {
      return new Lotto(IntStream.of(values)
              .mapToObj(LottoNumber::valueOf)
              .toList());
  }
```
메서드에 테스트를 위한 용도를 알리고 싶어서 정적 팩토리 메서드로 구현하려고하는데 어떻게 생각하시나요?
굳이 정적 팩토리 메서드를 생성할 필요 없이 생성자 + 주석으로 충분할까요?

감사합니다 :)

2024-05-29 08:11 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/LottoResult.java
> +    }
앗 감사합니다!

2024-05-29 08:20 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/LottoResult.java
> +        Price profit = new Price(INITIAL_PRICE);
맞습니다! Price에서 0원 객체 생성 책임을 가지는게 캡슐화 관점에서 좋을 것 같아요~
Price에서 생성하면 LottoResult 클래스의` INITIAL_PRICE `상수도 함께 제거할 수 있겠네요! 😀

2024-05-29 08:25 UTC, Starlight258 commented
@jinyoungchoi95 
리뷰해주신 사항들 덕분에 많이 배웠습니다 🙇‍♀️
감사합니다 ! 😁

2024-05-29 11:45 UTC, jinyoungchoi95 commented on src/test/java/org/duckstudy/model/lotto/LottosTest.java
> +                    .toList();
아뇨 프로덕션에 Test라는 것을 명시하라라는 뜻은 아니었어요. 별도 생성하는 메소드는 테스트에 정의하는 걸 말씀드린 것이었어요.

테스트를 위한 생성자라기보다는 다양한 형태의 생성자는 객체 생성의 유연성을 높여주기 때문에 권유드린 것이었고, 이를 정적 팩토리 메소드로 표현하는 것은 달라요. 정적 팩토리 메소드와 생성자 그리고 메소드 이 3개는 엄연히 다른 존재들이에요.

테스트를 위한 메소드를 만들지 말라라는 것은 테스트를 위해서 객체의 행위가 추가되지 말라는 뜻이고, 생성자는 안정적인 객체 생성만 보장한다면 유연한 객체 생성을 도와주기 때문에 권장하기도 하는 것이에요. 그리고 정적 팩토리 메소드는 사실상 static이기 때문에 객체지향과 멀어지는 지름길이 될 수도 있고요.

2024-05-29 11:47 UTC, jinyoungchoi95 approved these changes
안녕하세요 명지님 😃

피드백 잘 반영해주셨네요. 다음 미션 진행을 위해 머지하겠습니다.

감사합니다🙇‍♂️

2024-05-29 11:47 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/Price.java
> +    }
해당 메소드는 여기서만쓰이니 private으로 변경해주어야할 것 같아요.

2024-05-29 11:47 UTC, jinyoungchoi95 commented on src/main/java/org/duckstudy/model/lotto/LottoNumber.java
> +    }
IntStream을 적절하게 활용하여 `List<LottoNumber>`를 생성하는 방법을 고민해보시면 좋을 것 같아요.

2024-05-29 12:22 UTC, Starlight258 commented on src/test/java/org/duckstudy/model/lotto/LottosTest.java
> +                    .toList();
아 그렇군요 제가 잘못 이해했네요 !! 감사합니다 !

테스트를 위한 별도의 메서드는 테스트 코드 내에서 정의하고, 프로덕션 코드에서는 테스트를 위한 코드를 추가하지 않아야겠네요!
그리고 생성자를 사용해서 객체 생성을 유연하게 제공할 수 있고,
 정적 팩토리 메서드는 클래스 수준에서 동작하기 때문에 객체 지향과 멀어지겠네요!
 
 반영해서 수정하겠습니다. 답변 감사합니다 😊

2024-05-29 12:39 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/Price.java
> +    }
맞습니다..! 감사합니다 !

2024-05-29 15:06 UTC, Starlight258 commented on src/main/java/org/duckstudy/model/lotto/LottoNumber.java
> +    }
IntStream을 이용하면 같은 기능을 더 간결하게 작성할 수 있겠네요 !!

2024-05-29 15:18 UTC, Starlight258 commented
@jinyoungchoi95 
리뷰 반영했습니다! 
세심하게 봐주셔서 감사합니다 🙇‍♀️

2024-05-29 16:28 UTC, merged