[로또 미션] 문상휘 미션 제출입니다.
next-step/java-lotto-clean-playground pull request #28
Opened 2024-06-03 08:32 UTC by moonwhistle

6/3

* 로또 1,2 단계 2차 수정본 및 3,4단계 제출입니다.

* 로또 1,2 단계 코드리뷰 리펙터링 사항 모두 반영하였습니다!

* LastWeekLottoNumber => LottoNumberParser 로 변환하였습니다.

* 4단계 수동 로또 번호를 입력받는 기능 구현에서 수동 로또 번호들을 일급컬렉션으로 관리하기 위해 PassiveLottoNumber 클래스를 생성하였습니다.

* 이번에 Dto를 처음 구현해봤는데, 저런 형식으로 구현하는게 맞는지 피드백 주시면 감사하겠습니다!!

* Dto의 toString 메서드를 통해 OuputView 에 값을 넘겨주어 로또 랭크를 출력하였습니다.

* Controller 에 있는 List lottoRankDtos = lottoRanks.entrySet().stream().map(rank -> new LottoRankDto(rank.getKey(), rank.getValue())).toList(); 이 코드의 경우 �Stream Map을 학습하고 챗 gpt 코드를 참고하여 구현하였습니다. ㅠ

* Enum에서 OutputView 에 직접적으로 값을 전달하지 않게 하여 의존을 끊어냈지만, 크게 달라진 부분은 없는 것 같습니다.

* Lotto의 경우 4단계 기능 구현을 위해 크게 두 가지(자동 로또, 수동 로또) 경우로 나누어 생각하였고 이에 따라 생성자를 오버로딩 하였는데 이것이 가능한지 궁금합니다...!

* 테스트 코드의 경우 최대한 경우를 나누어 작성하였습니다.

2024-06-05 07:36 UTC, sosow0212 requested changes
구조적으로 잘 설계해주셔서 리뷰하기에도 굉장히 편했습니다 👍

DTO를 처음 써보셨는데 잘 접근하신 것 같아요! 다만 현재는 DTO에 toString()을 오버라이딩해서 뷰에서 할 역할을 대신하는 것 같은데 이 부분 확인해보면 좋을 것 같습니다!
추가적으로 인덴트 2가 넘는 것들도 스트림 혹은 메서드 분리를 통해 요구사항 지켜주세요~

질문하신 Enum에서도 단순 값을 관리해도 되지만, 책임에 맞는 로직을 나눠줄 수 있으면 분리해주면 좋을 것 같아요!! 수고하셨습니다 👍

2024-06-05 07:36 UTC, sosow0212 commented on src/README.md
> +### 기능 요구사항
이건 선택인데 기능 요구사항 만들 때 어떤 모델을 만들 것이고, 어떻게 사용하면 좋을지 적어보는 것도 구조적인 설계를 할 때 도움이 되는 것 같습니다.
꼭 해야된다는 아니니깐 편하신대로 하시면 됩니다!

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LastWeekLottoNumber.java
> +public class LastWeekLottoNumber {
메서드 순서 맞춰주세요!

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LastWeekLottoNumber.java
> +    public LastWeekLottoNumber(String LastWeekLottoNumber, int bonusBall) {
```suggestion
    public LastWeekLottoNumber(String lastWeekLottoNumber, int bonusBall) {
```

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LastWeekLottoNumber.java
> +        }
숫자가 아니라면 어떻게 될까요?
List<Integer> 필드가 아닌 List<LottoBall>과 같이 원시값포장해서 역할을 위임하는 것은 어떨까요!

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/Lotto.java
> +    private final List<Integer> lottoNumber;
여기도 마찬가지로 원시값 포장해서 사용하면 좋을 것 같아요!

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/Lotto.java
> +    private void sortLottoNumber(List<Integer> lottoNumber) {
오 createLottoNumber에서는 만들어주는 역할만 하고, 섞어주는 건 Lotto의 책임으로 보셨네요 👍

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LottoNumberParser.java
> +        }
인덴트가 2라서 요구사항과 맞지 않습니다!
메서드를 분리하거나 혹은 stream으로 수정해보면 좋을 것 같습니다~

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LottoRank.java
> +import java.util.*;
import에 와일드카드는 지양해주세요! (구글 자바 컨벤션 참조)

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LottoRank.java
> +    private final Map<String, Integer> lottoRank;
Map에서 Key, Value를 아는데 오래 걸릴 것 같아요.
각각 어떤 의미인지 파악하기 힘들 것 같은데 이 또한 원시값포장을 하거나 다른 형태로 풀어보면 어떨까요?

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LottoRank.java
> +        }
여기도 인덴트2 입니다!

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LottoRank.java
> +    }
checkBonusNumber라는 네이밍은 throw Exception을 할 것 같은 느낌이 들어요!
boolean을 리턴하니 조금 더 적합한 네이밍으로 리팩토링 하면 좋을 것 같습니다 ~

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LottoRankDto.java
> +package domain;
dto가 도메인에 들어간 이유가 궁금합니다!

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/domain/LottoRankDto.java
> +    }
dto에 비즈니스 로직이 들어가도 될까요? 이 부분 한 번 찾아보시면 좋을 것 같습니다~

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/controller/LottoController.java
> +        List<LottoRankDto> lottoRankDtos = lottoRanks.entrySet().stream().map(rank -> new LottoRankDto(rank.getKey(), rank.getValue())).toList();
객체지향 생활체조 4번 참고해서 리팩토링해주세요!

2024-06-05 07:36 UTC, sosow0212 commented on src/main/java/controller/LottoController.java
> +        }
View 패키지에 Dto를 두면 MVC에서 컨트롤러는 뷰에 의존해도 되니 로직이 더 깔끔해질 것 같아요!
toString 같은 경우는 Dto가 View의 로직을 수행하는 것 같은데 이 부분도 함께 고쳐주세요

2024-06-05 07:36 UTC, sosow0212 commented on src/test/java/domain/LottoNumberGeneratorTest.java
> +        final List<Integer> expected = fakeLottoNumberGenerator.getRandomLottoNumber();
Interface interface = new FakeInterface();

이렇게 해야 인터페이스의 구현체가 잘 들어갔는지 확인할 수 있을 것 같아요!

2024-06-05 07:36 UTC, sosow0212 commented on src/test/java/domain/LottoNumberParserTest.java
> +        final String inputLastWeekNumber = "1,2,3,4,5,6";
이건 단지 궁금해서 남기는데요!
테스트 필드에만 final을 붙이시는 이유가 있는지 궁금합니다

2024-06-05 07:36 UTC, sosow0212 commented on src/test/java/domain/LottoNumberParserTest.java
> +        final List<Integer> actual = List.of(1, 2, 3, 4, 5, 6);
1. `// when` 이렇게 다른 부분도 공백 한 칸씩 추가해주면 더 보기 좋을 것 같아요 ㅎㅎ
2. given-when-then에서 각 부분에 어떤 것들이 들어오는지 다시 공부해보시면 좋을 것 같습니다! 실행부가 들어가야하는데 actual이 선언되네요! 이는 given에서 선언해야할 것 같습니다.
3. `inputLastWeekNumber`에서 숫자가 아닌 문자열이 들어가면 예외가 발생할텐데 이런 경우처럼 예외 케이스도 테스트 해주세요~ (이미 있다면 `@Nested` 어노테이션을 활용해서 같은 관심사의 테스트는 묶어줘도 좋을 것 같아요)

2024-06-05 07:36 UTC, sosow0212 commented on src/test/java/domain/LottoPriceTest.java
> +        final List<Integer> expected = List.of(5000,50000,1500000,30000000,2000000000);
정렬 확인해주세요!

2024-06-18 02:30 UTC, moonwhistle commented on src/README.md
> +### 기능 요구사항
사다리 미션 부터 열심히 구현해보겠습니다..!!

2024-06-18 02:30 UTC, moonwhistle commented on src/main/java/domain/LastWeekLottoNumber.java
> +public class LastWeekLottoNumber {
메서드 순서 변경하였습니다!

2024-06-18 02:32 UTC, moonwhistle commented on src/main/java/domain/LastWeekLottoNumber.java
> +    public LastWeekLottoNumber(String LastWeekLottoNumber, int bonusBall) {
변수명 컨벤션 수정하였습니다!

2024-06-18 02:43 UTC, moonwhistle commented on src/main/java/domain/LastWeekLottoNumber.java
> +        }
리펙터링 하다보니, LottoParser 클래스랑 LastWeekLottoNumber 클래스랑 하는 역할이 겹쳐 LastWeekLottoNumber 클래스 삭제하였습니다!

2024-06-19 04:30 UTC, moonwhistle commented on src/main/java/domain/Lotto.java
> +    private final List<Integer> lottoNumber;
원시값 포장하여 사용하도록 코드 수정하였습니다!

2024-06-19 04:31 UTC, moonwhistle commented on src/main/java/domain/Lotto.java
> +    private void sortLottoNumber(List<Integer> lottoNumber) {
넵 ㅎㅎ 감사합니다!

2024-06-19 04:32 UTC, moonwhistle commented on src/main/java/domain/LottoRank.java
> +import java.util.*;
지양하겠습니다!

2024-06-19 04:35 UTC, moonwhistle commented on src/main/java/domain/LottoNumberParser.java
> +        }
LottoNumber 클래스 추가하면서 해당 로직은 필요없을 거 같다는 생각이 들어 삭제하였습니다 ! (LottoNumber 클래스에 숫자 범위 예외 메서드 추가하였습니다)

2024-06-19 06:08 UTC, moonwhistle commented on src/main/java/domain/LottoRank.java
> +    private final Map<String, Integer> lottoRank;
List<LottoRankDto> 형식으로 받도록 수정하였습니다!

2024-06-19 06:13 UTC, moonwhistle commented on src/main/java/domain/LottoRank.java
> +        }
스트림 사용하여 인덴트 수정하였습니다!

2024-06-19 06:19 UTC, moonwhistle commented on src/main/java/domain/LottoRank.java
> +    }
구글링을 통해 boolean 값 메서드 네이밍 참고하여 수정하였습니다!

2024-06-19 06:21 UTC, moonwhistle commented on src/main/java/domain/LottoRankDto.java
> +package domain;
dto 에 대해 찾아보다 보니, 데이터를 전송해주는 것에 있어서 중점적으로 역할을 해야 한다고 생각하여 view에 데이터만 던져줄 수 있도록 domain에 작성하였습니다! 틀렸다면 수정하겠습니다

2024-06-19 06:21 UTC, moonwhistle commented on src/main/java/domain/LottoRankDto.java
> +    }
dto 는 데이터 전달에 중점적인 역할을 하기 때문에 비지니스 로직이 들어가는 것은 적절치 않다는 것을 깨달았습니다!

2024-06-19 06:24 UTC, moonwhistle commented on src/main/java/controller/LottoController.java
> +        List<LottoRankDto> lottoRankDtos = lottoRanks.entrySet().stream().map(rank -> new LottoRankDto(rank.getKey(), rank.getValue())).toList();
리펙터링 하였습니다!

2024-06-19 07:45 UTC, moonwhistle commented on src/main/java/controller/LottoController.java
> +        }
그럼 만일 dto 을 view 패키지에 두게 되면, toString 에 작성한 로직을 그대로 사용해도 되는건지 궁금합니다!

2024-06-19 08:01 UTC, moonwhistle commented on src/test/java/domain/LottoNumberParserTest.java
> +        final String inputLastWeekNumber = "1,2,3,4,5,6";
테스트의 경우 값이 불변인 상태에서 테스트를 해야 한다고 어디서 본 적이 있어서 final 로 선언 하였습니다....! 굳이 안붙여도 된다면 붙이지 않겠습니다!

2024-06-19 08:04 UTC, moonwhistle commented on src/test/java/domain/LottoNumberGeneratorTest.java
> +        final List<Integer> expected = fakeLottoNumberGenerator.getRandomLottoNumber();
참고하여 리펙터링 하였습니다!!

2024-06-19 09:34 UTC, moonwhistle commented on src/test/java/domain/LottoPriceTest.java
> +        final List<Integer> expected = List.of(5000,50000,1500000,30000000,2000000000);
정렬 완료했습니다!

2024-06-19 09:34 UTC, moonwhistle commented on src/test/java/domain/LottoNumberParserTest.java
> +        final List<Integer> actual = List.of(1, 2, 3, 4, 5, 6);
코드 리뷰를 통해 전체적인 테스트를 확인해보니 왜 저렇게 작성했는지 모를 정도로 개판인것 같았습니다.... 테스트 코드 리펙터링 완료하였습니다!

2024-06-22 19:15 UTC, sosow0212 approved these changes
고민 많이한게 느껴집니다 👏
리뷰는 참고만 해주시고 다음 미션부터 반영해주시면 될 것 같아요!
사다리가 진짜 어려운데 객체 설계 꼼꼼하게 하고 다음 미션 진행하면 좋을 것 같습니다.
혹시나 추가적으로 궁금한게 있다면 카톡으로 질문해주세요!

수고 많으셨습니다 👍

2024-06-22 19:15 UTC, sosow0212 commented on src/main/java/domain/LottoPrice.java
> +    public static int getLottoPrice(String sameLottoNumber) {
요구사항 잘 지켰네요👍

2024-06-22 19:15 UTC, sosow0212 commented on src/main/java/domain/LottoRankBundle.java
> +            List<Integer> lottoNumber = lotto.getLottoNumber().stream().map(LottoNumber::getLottoNumber).toList();
객체지향생활체조 4번에 보시면 한 줄에 점 하나씩! 가독성이 더 좋아집니다 ㅎㅎ

2024-06-22 19:15 UTC, sosow0212 commented on src/main/java/view/LottoRankDto.java
> +    }
toString은 디버깅 용도로 많이 사용합니다 ㅎㅎ 잘못된 건 아니지만 이 부분은 View에서 하는 것이 응집성 면에서 더 좋을 것 같다고 개인적으로는 생각합니다!

2024-06-22 19:15 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +        System.out.println("\n수동으로 구매할 로또 수를 입력해 주세요.");
[링크](https://velog.io/@jiminnote/JAVA%EC%A4%84%EB%B0%94%EA%BF%88-OS%EC%97%90-%EB%A7%9E%EA%B2%8C-%EC%B2%98%EB%A6%AC%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95) 참고해보시면 좋을 것 같아요!

2024-06-23 03:51 UTC, merged