[2주차] 로또 - 클린코드
next-step/java-lotto-clean-playground pull request #65
Opened 2024-10-02 14:35 UTC by sansan20535

안녕하세요!! 바쁘신 스케줄 중에도 시간 내어 리뷰해주셔서 정말 감사합니다 : ) 많이 배우도록 하겠습니다..!!

# 🚀 기능 구현 🚀
* README.md를 참고해주시면 감사할 것 같습니다 : )

# ❓ 질문 사항 ❓

*  테스트를 하면서 enum 클래스의 필드 값이 변화되는데, 이것이 다른 테스트의 결과에도 영향을 가져와 @BeforeEach로 초기화를 하기로 했습니다. 그러는 과정에서 enum클래스는 상속이 되지 않아 테스트용 메소드를 하나 만들어놓았는데 이에 대한 해결 방법이 궁금합니다..!!

# 🔧 수정 사항 🔧
* 이번에 시간이 많이 부족해서 예외처리에 대해 신경을 쓰지 못했습니다. 이후 리뷰반영과 함께 리팩토링하겠습니다.

2024-10-04 10:52 UTC, kokodak requested changes
안녕하세요 의진님! 미션 정말 고생 많으셨습니다 👏

객체 분리에 신경을 쓰신게 느껴졌고, 테스트도 꼼꼼하게 작성해주신 것이 너무 좋았어요.

남기신 질문 사항들은 코멘트로 남겨두었고, 그외에 전반적인 리뷰를 코멘트로 남겨두었어요.

PR 본문에 남겨주셨듯이, 예외 처리도 추후에 추가되면 더 완성도 있는 코드가 될 것 같아요. 예외 처리까지 파이팅입니다 😄

2024-10-04 10:52 UTC, kokodak commented on src/main/java/util/InputFromUser.java
> +    private static final Scanner scanner = new Scanner(System.in);
Scanner를 이용한 입력 부분을 따로 분리해주셨군요! InputView가 존재하지만, 이를 한번 더 분리해주신 이유가 있을까요?

2024-10-04 10:52 UTC, kokodak commented on src/main/java/view/InputView.java
> +package view;
저 개인적으로는, view 계층은 사용자와 가장 맞닿아 있는 곳이라 생각하는데요! 의진님이 생각하신 view 패키지의 역할은 무엇인가요?

2024-10-04 10:52 UTC, kokodak commented on src/main/java/util/InputFromUser.java
> +package util;
util 패키지는 무엇을 담을 수 있는 패키지인가요? 어쩌면 이것저것 다 담을 수 있는 만능 패키지가 될 수도 있을 것 같다는 우려가 있어요.

패키지를 나누는 이유가 무엇인지 고민해보면 좋을 것 같습니다.

2024-10-04 10:52 UTC, kokodak commented on README.md
> +# 🚀1단계 - 로또 자동구매🚀
리드미를 잘 작성해주셨네요! 👏
요구 사항과 구현 사항을 정리했을 때, 의진님이 느끼신 장점이 있었나요?

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/LottoCalculator.java
> +    private static final int LOTTO_COST = 1000;
로또 가격을 상수로 추출해 주셨군요! 적절한 이름을 붙여주셔서, 코드를 읽는 입장에서 1000 이라는 숫자의 의미를 이해하는데 수월했습니다 👍

로또 가격에 대한 관리 포인트를 한 곳으로 줄인다는 관점에서도 좋은 것 같아요.

2024-10-04 10:52 UTC, kokodak commented on src/main/java/controller/LottoController.java
> +        printAllLottos(passiveLottos, autoLottos);
프로그램의 흐름이 요구사항의 흐름과 살짝 다른 것 같아요!

2024-10-04 10:52 UTC, kokodak commented on src/main/java/util/LottoNumberConvertor.java
> +    public static List<Integer> convertLottoNumbers(final String lottoNumbers) {
```suggestion
    public static List<Integer> convert(final String lottoNumbers) {
```

이런 메서드명은 어떠신가요?
클래스명을 통해 로또 번호에 대한 컨버팅이 이루어진다는 맥락을 이해할 수 있어서, 메서드명은 행위만 드러나게 적어도 좋을 것 같아요.

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/LottoMakeStrategy.java
> +    public Lottos makeLottos();
<img width="724" alt="image" src="https://github.com/user-attachments/assets/65a320e9-4b29-4406-abe1-117d261193ee">

interface에서는 접근 제어자, static, final 등의 키워드를 명시할 필요가 없다고 하네요.
이런 불필요한 코드는 IDE의 도움을 받아서 제거해도 좋을 것 같습니다.

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/LottoMakeStrategy.java
> +    public static final int LOTTO_NUMBER_COUNT = 6;
interface는 특정한 API들을 **범용적으로 설계**하기 위해 사용하는 기술적 수단이에요.

그런 의미에서, interface에 들어가는 상수는 **어떤 구현체에 상관없이 범용적으로 사용되는 값**이어야 할 것이구요.

다만, 현재 `LOTTO_NUMBER_COUNT` 상수는 특정 구현체에서만 사용되는 상수인 것 같네요.  

그 말은, `LOTTO_NUMBER_COUNT` 상수는 특정 구현체의 구현을 위해 사용되는 상수이니, 위치해야 할 곳은 적어도 이 interface는 아닐 것 같아요.

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/LottoMakeStrategy.java
> +    public static final int START_EXTRACT_INDEX = 0;
클래스 이후에 한칸 개행을 공통적인 컨벤션으로 잡으신 것 같아요. 별 건 아니지만, 사소한 부분이 코드의 완성도를 높여준다고 생각합니다!

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/LottoMakeStrategy.java
> +public interface LottoMakeStrategy {
로또 생성에 대한 행위를 추상화하여 인터페이스로 추출해주셨군요! 👍

다만, 사실 인터페이스를 따로 빼지 않고 생성자로 원하는 로또 값을 주입해주는 방법도 존재할 것 같아요.

궁금한 점은, 왜 전략을 두셨나요? 왜 추상화가 필요하다고 생각했는지 궁금해요.

또한, 생성자로 주입하는 것과는 어떤 다른 점이 있었나요?
인터페이스로 추출하는 것과, 인터페이스를 사용하지 않고 생성자만 사용하는 것 각각 어떤 장단점이 있을까요?

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/RandomLottosMakeStrategy.java
> +    public final List<Integer> lottoNumbers = new ArrayList<Integer>(
public으로 열어둔 이유가 있을까요?

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/RandomLottosMakeStrategy.java
> +                    return new Lotto(lotto);
오! 리드미에 작성해주셨던 고민사항 내용이네요 ㅎㅎ

되게 좋은 접근인 것 같아요. 한번 선언된 lottoNumbers 필드 값을 매번 재활용할 수 있겠네요. 배워갑니다 👍

한가지 궁금한 점은, 재활용이 목적이라면 static한 필드로 빼내는 것은 어떨까요?

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/LottoCalculator.java
> +        }
의진님은 for문과 stream을 사용하는 본인만의 기준이 있으신가요?

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/WinningLotto.java
> +    private final int bonusNumber;
상속을 사용하여 WinningLotto 클래스를 구성해주셨네요.

저는 개인적으로 상속을 선호하지 않는데요, 왜냐하면 객체간 결합도가 높아져서 의존성이 심화된다고 생각하기 때문이에요.

예를 들어, WinningLotto 클래스만 봤을 때, Lotto 클래스를 까보지 않는 이상 lottoNumber 필드의 존재 유무를 알 수 없고, super 를 호출했을 때 부모 클래스에서 어떤 일을 하는지도 알 수 없어요.

그래서 저는 개인적으로, [상속보다는 조합](https://tecoble.techcourse.co.kr/post/2020-05-18-inheritance-vs-composition/)을 사용하는 편입니다.

의진님은 상속을 사용했을 때, 어떤 장단점이 따라온다고 생각하시나요?

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/WinningLottosStatus.java
> +    SIX_CORRECT_LOTTOS(6, 2000000000, 0, false);
오!! Enum으로 로또 당첨에 대한 정보를 잘 묶어서 정리해주셨네요 👍👍👍

확실히 Enum을 사용하면, 비슷한 성격의 값들을 손쉽게 묶을 수 있다는 장점이 있는 것 같아요.

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/WinningLottosStatus.java
> +                .orElse(null);
null 값을 직접 다루는 것보다는, 꼴등 상태를 정의해서 그것을 반환하는 것이 좋을 것 같아요!

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/WinningLottosStatus.java
> +    }
정적 팩터리 메서드를 잘 정의해주셨네요! Enum을 잘 활용하신 것 같아요 👍

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/CorrectLottoNumbersCheck.java
> +public class CorrectLottoNumbersCheck {
의진님은 클래스를 정의할 때, 어떤 기준으로 유틸성 static 클래스인지 아닌지를 구분하시나요?

예를 들어, InputView 클래스 내부의 메서드는 왜 static으로 선언하셨고, CorrectLottoNumbersCheck 클래스 내부의 메서드는 static으로 선언하지 않으셨나요?

제가 생각하기에 저 둘은 성격이 비슷해 보이는데, static 여부가 달라서 질문 드렸어요.

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/CorrectLottoNumbersCheck.java
> +        if (winningLotto.getLottoNumber().contains(lottoNumber)) {
`당첨 번호가 포함되어 있는가?` 라는 메시지를 WinningLotto [객체에게 직접 물어보는게 어떨까요?](https://mangkyu.tistory.com/147)

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/CorrectLottoNumbersCheck.java
> +        return IS_NOT_CORRECT_LOTTO_NUMBER;
반환 값이 이분법적으로 나뉜다면, boolean 값을 반환하는 것이 더 명확할 것 같아요.

2024-10-04 10:52 UTC, kokodak commented on src/main/java/domain/CorrectLottoNumbersCheck.java
> +        return lotto.getLottoNumber().contains(lastWeekWinnerLotto.getBonusNumber());
위의 리뷰와 동일한 맥락입니다.
https://mangkyu.tistory.com/147

2024-10-04 10:52 UTC, kokodak commented on src/test/java/LottoCalculatorTest.java
> +        final int result = lottoCalculator.calculateAutoLottoCount(buyingCosts, passiveLottoCount);
테스트 작성 시에, 실제로 나온 값에 대한 네이밍은 관례적으로 `actual` 이라는 이름을 붙이는 것 같아요. 네이밍은 정답이 없는 분야이니, 적당히 참고해주시면 될 것 같아요!

2024-10-04 10:52 UTC, kokodak commented on src/test/java/LottoNumberConvertorTest.java
> +        Assertions.assertThat(result).usingRecursiveComparison().isEqualTo(expected);
테스트의 짬이 느껴지는데요..?

2024-10-04 10:52 UTC, kokodak commented on src/test/java/UpdateWinningLottosTest.java
> +    static Stream<Arguments> generateData() {
👍 👏👏
`@ParameterizedTest`를 잘 활용해주셨네요.. 의진님 고수시군요

2024-10-04 10:52 UTC, kokodak commented on src/test/java/UpdateWinningLottosTest.java
> +    }
이 부분에 대한 생각을 남겨보자면,

일단, 매번 초기화를 해줘야 하는 이유부터 파악을 해야겠죠. 가장 근본적인 이유는, 싱글턴으로 존재하는 Enum 인스턴스에 **lottoCount 라는 변화하는 값**을 필드로 넣은 것이 문제의 출발점입니다.

그렇다면 Enum 안에 있는 lottoCount를 제거하면 되지 않을까요? 이를 계산해서 저장하는 곳을 따로 만드는 것이 좋을 것 같아요.

추가로, Enum의 역할에 대해 다시 생각해 볼 필요가 있는 것 같아요. Enum에 변수 값이 들어간 순간부터, 이를 더 이상 `상수`라는 개념으로 보기 어려울 것 같습니다.

2024-10-08 10:43 UTC, sansan20535 commented on README.md
> +# 🚀1단계 - 로또 자동구매🚀
네 있습니다! 이전에는 이 기능, 저 기능 순서없이 구현하다보니 나중에 보면 주석이 있음에도 제가 이해하기 힘든 코드가 많았습니다. 하지만 이렇게 요구 사항과 구현 사항을 정리했을 때 제가 의도한 대로 코드를 작성했는지 쉽게 볼 수 있었고, 이후 추가적인 구현기능이 있더라도 비교적 쉽게 추가할 수 있었던 것 같습니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/controller/LottoController.java
> +        printAllLottos(passiveLottos, autoLottos);
사실 이 부분에 대해서도 고민이 많았는데 처음에는 '로또만들기 -> 로또 출력 -> 당첨 로또 업데이트 -> 결과 출력'의 흐름대로 작성했습니다. 하지만 이후 서비스 로직과 출력을 분리하는 게 가독성에 좋아보여서 배치했던 것인데 요구사항의 흐름이 더 중요한 것이 맞다고 느꼈습니다! 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/CorrectLottoNumbersCheck.java
> +public class CorrectLottoNumbersCheck {
저번 미션과 이번 미션을 통해 static의 여부에 대해서 고민해보았습니다.. 나름대로 생각해본 결과 static 클래스는 프로그램 전체에서 공통적으로 사용되는 로직을 주로 담으면 좋을 것 같다고 생각했습니다. 그런 의미로 CorrectLottoNumbersChecks는 로또번호를 확인하는 특정 로직을 수행해서 static으로 구현을 안 한 것같습니다. 하지만 이렇게 생각하면 InputView클래스 또한 입력이라는 특정 로직을 수행하므로 static 클래스를 지양하는 것이 맞다고 생각하게 되었습니다..!!

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/CorrectLottoNumbersCheck.java
> +        if (winningLotto.getLottoNumber().contains(lottoNumber)) {
아하..!! 저런 방법이 있었군요..!! 좋은 글까지 추천해주셔서 감사합니다..!!

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/CorrectLottoNumbersCheck.java
> +        return IS_NOT_CORRECT_LOTTO_NUMBER;
아하 말씀하신 대로 맞다 아니다는 boolean값이 맞는 것 같습니다..!! 수정해보겠습니다!! 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/CorrectLottoNumbersCheck.java
> +        return lotto.getLottoNumber().contains(lastWeekWinnerLotto.getBonusNumber());
여기도 객체의 역할로 정할 수 있었네요! 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/LottoCalculator.java
> +        }
저는 stream을 객체의 리스트를 다른 객체의 리스트로 반환할 때 주로 사용합니다..!! for문은 단순히 객체 안의 값을 이용하거나 업데이트 하는 경우 사용합니다!!

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/LottoMakeStrategy.java
> +    public static final int START_EXTRACT_INDEX = 0;
사소한 부분까지 확인해 주셔서 감사합니다!! 수정하겠습니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/LottoMakeStrategy.java
> +    public static final int LOTTO_NUMBER_COUNT = 6;
말씀해주신 대로 이는 구현체에서 선언해야할 상수인 것 같습니다! 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/LottoMakeStrategy.java
> +    public Lottos makeLottos();
아하 IDE에서 이런 점들도 확인할 수 있군요..! 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/RandomLottosMakeStrategy.java
> +    public final List<Integer> lottoNumbers = new ArrayList<Integer>(
코드를 잘못 작성한 것 같습니다..! 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/RandomLottosMakeStrategy.java
> +                    return new Lotto(lotto);
아하 엄청 좋은 의견 같습니다!! 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/WinningLottosStatus.java
> +    SIX_CORRECT_LOTTOS(6, 2000000000, 0, false);
맞습니다!! 안 그래도 ENUM타입으로 관리하면 좋을 것 같다고 생각했었는데, 조건에도 마침 나와서 좋았습니다!!

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/WinningLottosStatus.java
> +                .orElse(null);
아하!! 그러는 것이 더 의미가 분명한 거 같아서 좋습니다!!!

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/util/InputFromUser.java
> +package util;
저도 이번에 util에 대해서 고민을 많이 해보았는데... 프로그램 전체에 걸쳐서 필요한 기능을 util 패키지에 넣는 것이 맞는 것 같다고 생각했습니다!!(ex : 로또 번호 변환 -> 우승로또 입력, 수동로또 입력에 사용 등)

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/util/InputFromUser.java
> +    private static final Scanner scanner = new Scanner(System.in);
저는 '사용자 입력'과 '입력문구 출력'이라는 역할을 분리해서 보고 싶었습니다!! 그리고 이후 입력단계에서 잘못된 입력에 대해서 예외처리를 쉽게 할 수 있도록 하기 위해서 이렇게 분리했습니다!!

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/util/LottoNumberConvertor.java
> +    public static List<Integer> convertLottoNumbers(final String lottoNumbers) {
아하!! 저는 최대한 모든 메소드에 의미를 담고 싶었던 것인데 클래스명에서 이미 구별을 했으면 괜찮은 거 같군요! 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/view/InputView.java
> +package view;
저는 view 패키지의 역할은 사용자에게 정보를 제공하는 패키지라고 생각합니다!! 사용자가 어떤 행동을 해야하고, 그에 따라 어떤 결과를 얻을 수 있는지 정보를 제공하는 패키지라고 생각합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/test/java/LottoCalculatorTest.java
> +        final int result = lottoCalculator.calculateAutoLottoCount(buyingCosts, passiveLottoCount);
아하! 관례를 따라가는 것이 이후 좋은 영향이 있을 거 같습니다 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/test/java/UpdateWinningLottosTest.java
> +    static Stream<Arguments> generateData() {
아닙니다... 모두 보고 배운 겁니다 너무 감사합니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/test/java/UpdateWinningLottosTest.java
> +    }
정확하게 말씀해 주신 것 같습니다.. Enum은 변하지 않는 상수여야 하는데 업데이트를 하는 것이 맞는 것인가 생각을 했었습니다. 답이 의외로 간단했군요..! 감사합니다, 수정해보도록 하겠습니다 : )

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/LottoMakeStrategy.java
> +public interface LottoMakeStrategy {
저번 주에 배운 전략패턴을 직접 적용해보고 싶은 생각도 들었고, 가장 큰 이유는 이후 단계에서 수동 입력이 있는 경우를 보았기 때문입니다. makeLotto라는 하나의 공통된 목표가 있지만 그 안에서 동작하는 로직은 요구사항에 맞추어 달라질 수 있어야 한다고 생각했기 때문에 인터페이스로 구현했습니다. 생성자로 주입하지 않았던 것은 각 생성 전략마다 필요한 정보들이 다르고, 같은 동작방식을 따르지는 않다고 생각했기 때문에 인터페이스로 구현했습니다..!

2024-10-08 10:43 UTC, sansan20535 commented on src/main/java/domain/WinningLotto.java
> +    private final int bonusNumber;
저는 상속을 사용했을 때 중복되는 코드를 줄일 수 있다고 생각했습니다. WinnningLotto 또한 Lotto의 성질을 모두 가지고 있는 것이기 때문에 Lotto가 가진 필드와 메소드를 다시 언급할 필요가 없다고 생각해서 상속을 이용했습니다. 말씀하신대로 상속을 사용하면 부모에서 변한 사항들이 자식들에게 영향을 미쳐 심각한 문제가 발생할 수도 있을 것 같습니다..!! 조합이라는 개념을 처음 알게 되었는데 이 또한 좋은 방법인 것 같습니다. 정말 감사합니다 : )

2024-11-14 08:20 UTC, merged